### ISSUE TITLE
Start versioning the project using semantic versioning

### ISSUE THREAD

**Issue by juliendelplanque** [pharo-rdbms/Pharo-SQLite3#10]
So people can depend on the repository safely.

I think we should just start with a first version `v1.0.0`.

**Comment by astares** [comment]
Yes - is on my list (including a proper config for catalog)

**Comment by juliendelplanque** [comment]
I can do it if you want.
I do that for all my repositories.

**Comment by astares** [comment]
I'm already on it

**Comment by juliendelplanque** [comment]
Ok, cool.

**Comment by astares** [comment]
Old scheme was up to 1.4 version.

I now defined a 1.5.0 which also has a configuration in GitHub and Catalog.

![image](https://user-images.githubusercontent.com/5980033/70667037-3176b700-1c70-11ea-9a62-41eadcda9f00.png)


We should check loading from Catalog tomorrow after indexer was run.

**Comment by astares** [comment]
I checked - the config was indexed last night. So SQLite3 is able to load from catalog again.
We can close the issue
