### ISSUE TITLE
Set up branch protection to forbid direct modification of master branch

### ISSUE THREAD

**Issue by juliendelplanque** [pharo-rdbms/Pharo-SQLite3#11]
Like that we can make sure any change is reviewed before integration.

**Comment by astares** [comment]
A branch protection only means we need to have PR's - but an integrator can then still:
 - do a PR
 - merge it directly into the branch

No?

**Comment by juliendelplanque** [comment]
For sure, but then it just means that we trust integrators... Which should be the case else, the integrator should not be.

What do you think?

**Comment by astares** [comment]
Let's ask @PierceNg

**Comment by PierceNg** [comment]
On Wed, Dec 11, 2019 at 01:59:42AM -0800, Astares wrote:
> Let's ask @PierceNg 

I don't know what these phrases mean. Please define:

- branch protection of master
- direct modification

**Comment by PierceNg** [comment]
I don't know GH beyond the basics. Here integrator refers to those with write access to this repo, and currently that means all 7 members of team pharo-rdbms?

**Comment by gcotelli** [comment]
The branch protection can be configured in two modes:
- One does not allow to merge a PR if the CI is not passing and a configurable number of reviewers approves it, or push directly to the protected branch. Even for administrators. 
- The other mode allows that a repo admin merge a PR even if the other conditions are not met. However the UI will warn of that. And it allows direct push to the protected branch from the repo admins.
And this is pretty configurable, so you can select what CI tasks are required or if you want reviewers approval or not.
