### ISSUE TITLE
Add support for backups and connection, statement, cursor division of responsibilities

### ISSUE THREAD

**Issue by tblanchard** [pharo-rdbms/Pharo-SQLite3#12]
Add support for SQLite backups api.

See https://sqlite.org/c3ref/backup_finish.html#sqlite3backupinit and the article at https://www.oreilly.com/library/view/using-sqlite/9781449394592/re225.html

Clarifies responsibilities of Connection->Statement->Cursor.  Connections are databases, Statements can be executed, Cursors or ResultSets are basically iterators and only concerned with iteration and fetching.

**Comment by astares** [comment]
Merged - we can close the issue
