### ISSUE TITLE
Pharo SQL3 does not run in windows 10 

### ISSUE THREAD

**Issue by gabrielo33** [pharo-rdbms/Pharo-SQLite3#21]
i have loaded the project with this script 
```Smalltalk
Metacello new 
	repository: 'github://pharo-rdbms/Pharo-SQLite3/src';
	baseline: 'SQLite3';
	load 
```

and then i run the tests 

![image](https://user-images.githubusercontent.com/65148298/82621788-165a8c80-9baa-11ea-9787-eee27885a3aa.png)
 
can you help me.

**Comment by astares** [comment]
Runs fine for me on Windows10.

Definitely a local problem of your machine. Looks like the DLL is not found (as all are red). Click on the red icon to debug a test case to see the details.

**Comment by gabrielo33** [comment]
@astares thank you for help. it works now SQL3
