### ISSUE TITLE
Instance of SQLite3Library did not understand #stringFrom:at:

### ISSUE THREAD

**Issue by PowellDean** [pharo-rdbms/Pharo-SQLite3#60]
Running the following in a Playground:

| connection cursor |
connection := SQLite3Connection memory.
connection open.
connection execute: 'CREATE TABLE person(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  age INTEGER NOT NULL
);'.

connection execute: 'INSERT INTO person(name,age) VALUES (:name, :age);' with: {
  ':name' -> 'Guillaume'.
  ':age' -> 30 } asDictionary.

cursor := connection execute: 'SELECT * FROM person;'.
cursor rows

The walkback window shows the error raised at line 6 in the stringAt: method for the SQLite3PreparedStatement class.

The image is Pharo 12, 64-bit, on Ubuntu Linux 22.04
The same error appears when using a Pharo 10, 64-bit image on the same Ubuntu Linux 22.04
The same error also appears on my Windows 11 machine, running a Pharo 12 image (64-bit)

On Linux, the version of sqlite is: 3.31.1 2020-01-27 19:55:54 3bfa9cc97da10598521b342961df8f5f68c7388fa117345eeb516eaa837bb4d6

I've run just the create table command, and that executes with no issues. I can also run the execute: method and that returns acceptable. It's only when I attempt to fetch a row that the walkback occurs.

**Comment by astares** [comment]
Works with Pharo 9.

Method is in Pharo 9 extension package, looks like this needs to be loaded in P10/11/12

<img width="505" alt="image" src="https://user-images.githubusercontent.com/5980033/233267077-c1d3ccb1-623d-4b0f-895a-8795a7ab7e47.png">

**Comment by PowellDean** [comment]
I've loaded that method to SQLite3Library and done some testing, both with in-memory databases and disk-based database files. so far, everything is now working.

Looks good. you may close the issue.

**Comment by gcotelli** [comment]
Blocked until #65 is fixed
